In [164]:
import numpy as np
from tqdm import tqdm

def numbers(x):
    if x == 'S':
        return 1
    elif x == "E":
        return 26
    else:
        return int(ord(x)-96)
    
text = open('inputs/day12.txt').read()
arr = np.array([[numbers(char) for char in list(line)] for line in text.split('\n')])

print(arr)

[[1 2 1 ... 1 1 1]
 [1 2 1 ... 1 1 1]
 [1 2 1 ... 1 1 1]
 ...
 [1 2 1 ... 1 1 1]
 [1 2 3 ... 1 1 1]
 [1 2 3 ... 1 1 1]]


In [165]:
arr_letters = np.array([[char for char in list(line)] for line in text.split('\n')])


start = (np.where(arr_letters == 'S')[0].item(), np.where(arr_letters == 'S')[1].item(), 0)
start_coord = start[:2]
end_coord = (np.where(arr_letters == 'E')[0].item(), np.where(arr_letters == 'E')[1].item())

In [166]:
main_list = [start]
coords = [start_coord]
c = 0
answer = 0

for pos in main_list:
    c = pos[2] + 1
    cell_list = [(pos[0]-1, pos[1], c), (pos[0]+1, pos[1], c), (pos[0], pos[1]-1, c), (pos[0], pos[1]+1, c)]
    for cell in cell_list:
        if (cell[0] < 0) | (cell[0] > arr.shape[0]-1) | (cell[1] < 0) | (cell[1] > arr.shape[1]-1):
            # Out of bounds
            pass
        elif arr[cell[:2]] - arr[pos[:2]] > 1:
            # Too High
            pass
        elif cell[:2] in coords:
            # Already visited
            pass
        else:
            main_list.append(cell)
            coords.append(cell[:2])
            if cell[:2] == end_coord:
                print("Finished")
                answer = (cell[2])
    
    if end_coord in coords:
        break

print(f"Part 1 answer: {answer}")


Finished
Part 1 answer: 383


In [167]:
answers = []

for i in tqdm(range(len(arr))):
    for j in range(len(arr[1])):
        if arr[i,j] == 1:
            main_list = [(i,j,0)]
            coords = [(i,j)]
            c = 0
            answer = 0

            for pos in main_list:
                c = pos[2] + 1
                cell_list = [(pos[0]-1, pos[1], c), (pos[0]+1, pos[1], c), (pos[0], pos[1]-1, c), (pos[0], pos[1]+1, c)]
                for cell in cell_list:
                    if (cell[0] < 0) | (cell[0] > arr.shape[0]-1) | (cell[1] < 0) | (cell[1] > arr.shape[1]-1):
                        # Out of bounds
                        pass
                    elif arr[cell[:2]] - arr[pos[:2]] > 1:
                        # Too High
                        pass
                    elif cell[:2] in coords:
                        # Already visited
                        pass
                    else:
                        main_list.append(cell)
                        coords.append(cell[:2])
                        if cell[:2] == end_coord:
                            answer = (cell[2])
                            answers.append(answer)

                if end_coord in coords:
                    break
                    
print(f"Part 2 answer: {min(answers)}")

100%|███████████████████████████████████████████| 41/41 [00:38<00:00,  1.05it/s]

Part 2 answer: 377
